AWSTemplateFormatVersion: 2010-09-09
Description: Create EFS,Dynamo

Parameters:
  NetworkStackName:
    Type: String
    # Default: network
    Default: sample-lambda
  EfsPath:
    Type: String
    Default: "/myefs"

Resources:
  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      PerformanceMode: maxIO
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: TestFileSystem
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticfilesystem:ClientMount"
              - "elasticfilesystem:ClientWrite"
              # - "elasticfilesystem:ClientRootAccess"
            Principal:
              AWS: "*"

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-PublicSubnet1
      SecurityGroups:
      - Fn::ImportValue: !Sub ${NetworkStackName}-VpcDefaultSecurityGroupId

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet2
      SecurityGroups:
      - Fn::ImportValue: !Sub ${NetworkStackName}-VpcDefaultSecurityGroupId

  AccessPointResource:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: !Ref FileSystemResource
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: !Sub ${EfsPath}

  DynamoResource:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CfnImportSampleTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  EfsPath:
    Description: Efs path
    Value: !Sub ${EfsPath}
    Export:
      Name: !Sub ${AWS::StackName}-EfsPath

  EfsAccessPointArn:
    Description: Efs accesspoint arn
    Value: !GetAtt
      - AccessPointResource
      - Arn
    Export:
      Name: !Sub ${AWS::StackName}-EfsAccessPointArn

  DynamoTableName:
    Description: Dynamo table name
    Value: !Ref DynamoResource
    Export:
      Name: !Sub ${AWS::StackName}-DynamoTableName
